import Head from 'next/head'
import React from 'react'

// import components
import Sidebar from '../templates/sidebar'
import Home1 from '../templates/home'
import About from '../templates/about'
import Service from '../templates/service'
import Portfolio from '../templates/portfolio'
import Testimonial from '../templates/Testimonials'
import Contact from '../templates/contact'

// import data
import { data } from '../data/data'


export default function Home() {
  return (
    <React.Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="site">
          <Sidebar data = {data.sidebar} />
          <Home1 data = {data.home} />
          <About data = {data.about} />
          <Service data = {data.service} />
          <Portfolio data = {data.portfolio} />
          <Testimonial data = {data.testimonial}/>
          <Portfolio data = {data.blog}/>
          <Contact data = {data.contact}/>
        </div>
      </main>
    </React.Fragment>
  )
}
